Novo visual da página Home (Landing page)
giovannialves01/API-RGBA pull request #27
Opened 2021-04-05 13:43 UTC by Syank

Conforme o feedback na última entrega, a página de boas-vindas teve o seu visual reformulado

Ainda existem alguns complementos a serem adicionados à página para sua total funcionalidade:
- Ajustar novamente o "slider"
- Ajustar o menu de navegação
- Criar as rotas "clicáveis", isto é, adicionar as funcionalidades de redirecionamento quando o usuário clicar em algo

**Nota:**
_Não apagar a branch após o merge, será utilizada novamente_

2021-04-05 13:44 UTC, Syank commented
Não apagar a branch após o merge, será utilizada novamente 😀

2021-04-05 15:00 UTC, barbaraport approved these changes

2021-04-05 15:28 UTC, giovannialves01 requested changes, later dismissed
Se der, tirar a barra horizontal e arrumar o tamanho do quadrado do "certificado".

2021-04-05 16:30 UTC, Syank commented
> Se der, tirar a barra horizontal e arrumar o tamanho do quadrado do "certificado".

Qual barra horizontal?

O que tem o tamanho do "certificado"?

Tira print e posta aqui pra eu entender o que precisa mudar

😟

2021-04-06 11:43 UTC, giovannialves01 approved these changes

2021-04-06 17:58 UTC, Barbara-BB commented
Alguns comentários do meu irmão nos prints, mas não precisa mexer agora. A opinião dele foi baseada na experiência dele com usabilidade e design. Ele disse que melhorou muito em relação ao anterior. Eu também concordo.
A minha única preocupação é com relação às imagens das pessoas, precisamos certificar sobre não ter direitos autorais, pois podemos ser questionados sobre isso.
![paginahome](https://user-images.githubusercontent.com/60778277/113756844-44748c80-96e8-11eb-83c4-9c4d067bf875.png)
![paginainicial2](https://user-images.githubusercontent.com/60778277/113756872-4dfdf480-96e8-11eb-8e05-508e724befd5.png)
![paginahome3](https://user-images.githubusercontent.com/60778277/113756903-57875c80-96e8-11eb-9248-6d3636a1dad2.png)
![paginahome4](https://user-images.githubusercontent.com/60778277/113756935-653ce200-96e8-11eb-9370-195b4c6f00e5.png)

2021-04-06 18:06 UTC, Barbara-BB approved these changes
Aprovado, coloquei os comentários anteriormente.

2021-04-06 18:25 UTC, merged